import clsx from "clsx";
import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { TbPlus } from "react-icons/tb";
import { Layout } from "../components/Layout";
import { MyFeed } from "../components/MyFeed";
import { MyPosts } from "../components/MyPosts";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const {
    isLoading,
    isFetching,
    data: session,
  } = trpc.useQuery(["auth.getSession"]);

  const [isMyPosts, setIsMyPosts] = useState(false);

  const { isLoading: isLoadingPosts, data: posts } = trpc.useQuery([
    "post.getPosts",
    {
      isMyPosts,
    },
  ]);

  const activeTabStyle = "bg-red-200 font-bold";

  return (
    <>
      <Head>
        <title>Jrnlr - T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <header>
          {!!session ? (
            <div className="flex items-center">
              <div className="mr-3 h-12">
                <Image
                  className="rounded-full"
                  src={session?.user?.image ?? ""}
                  alt={session?.user?.name ?? ""}
                  width={48}
                  height={48}
                />
              </div>
              <p className="text-2xl font-bold leading-none">Home</p>
              {/* <button onClick={() => signOut()}>Sign Out</button> */}
            </div>
          ) : isLoading && isFetching ? (
            "loading..."
          ) : (
            <button onClick={() => signIn("google")}>Sign In</button>
          )}

          {/* <label
            htmlFor="default-toggle"
            className="inline-flex relative items-center cursor-pointer"
          >
            <input
              type="checkbox"
              value=""
              id="default-toggle"
              className="sr-only peer"
            />
            <div className="w-11 h-6 bg-pink-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-pink-300 dark:peer-focus:ring-pink-800 rounded-full peer dark:bg-pink-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-pink-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-pink-600 peer-checked:bg-pink-600"></div>
            <span className="ml-3 text-sm font-medium text-pink-900 dark:text-pink-300">
              Toggle me
            </span>
          </label> */}
        </header>

        <nav className="mt-5 flex rounded-[10px] border border-red-200 p-px">
          <button
            className={clsx(
              "h-8 flex-1 rounded-lg text-gray-800",
              !isMyPosts && activeTabStyle
            )}
            onClick={() => setIsMyPosts(false)}
          >
            Feed
          </button>
          <button
            className={clsx(
              "h-8 flex-1 rounded-lg text-gray-800",
              isMyPosts && activeTabStyle
            )}
            onClick={() => setIsMyPosts(true)}
          >
            Drafts
          </button>
        </nav>

        <main className="container mx-auto mt-4">
          {isLoadingPosts ? (
            <p>Loading posts...</p>
          ) : isMyPosts && posts ? (
            <MyPosts posts={posts} />
          ) : !isMyPosts && posts ? (
            <MyFeed posts={posts} />
          ) : null}
        </main>

        <Link href="/create">
          <button className="absolute bottom-5 right-5 flex h-12 w-12 items-center justify-center rounded-full bg-red-200 text-black">
            <TbPlus className="h-5 w-5 text-inherit" />
          </button>
        </Link>
      </Layout>
    </>
  );
};

export default Home;
